### ISSUE TITLE
Clarify the software side

### ISSUE THREAD

**Issue by probonopd** [rene-mt/vitotronic-interface-8266#1]
Which software are you using to talk to the ESP8266 (send commands, receive information)?

**Comment by rene-mt** [comment]
I'm using the interface with _[FHEM](http://fhem.de/fhem.html)_ and the _[VCONTROL](http://fhem.de/commandref.html#VCONTROL)_ module. During development I also tested it with _[vcontrold](http://openv.wikispaces.com/vcontrold)_ and _[vclient](http://openv.wikispaces.com/vclient)_. Basically, if you know about the protocol, you also could simply use telnet for communication.

**Comment by probonopd** [comment]
Thanks. _Very_ cool project. Also interesting could be to implement an interface to communicate with the [Vitotrol App](http://www.viessmann.de/de/viessmann-apps/vitotrol-app.html)... although I am not sure whether the app always communicates via a Viessmann server - might need a proxy...

**Comment by rene-mt** [comment]
For that you first would need the network module / internet gateway for the heating (_Vitocom 100 LAN_), which is over 300 Euro. And then, yes, the app itself communicates over a Viesmann server. As far as I see it you need to register your heating plus the app there and then you can control it, while all commands always run over the internet / Viessmann server. Means: no internet connection, or problems at the Viessmann side - no heating control.

The charm of my solution, besides the price, is that I can control the heating via WiFi _inside_ my home network, without sharing data in some cloud. And if I want to do it from along the way I can connect via VPN and do it :) Plus: I can implement some fancy steering logic, based on sensors, times, holidays, whatever, in my home server, which is way beyond the capabilities of the Viessmann app.

Just to give some impression about the capabilities, also for monitoring/data collection, see this screenshot: ![heizung](https://cloud.githubusercontent.com/assets/4964846/20239004/93eedd6c-a8f7-11e6-8666-f685d3b1c363.png)

**Comment by probonopd** [comment]
>  you first would need the network module / internet gateway for the heating (Vitocom 100 LAN)

At least, _that's what they say_ ;-)
